### ISSUE TITLE
Run flank --version at beginning of step

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-steplib/bitrise-step-flank#3]
Currently there's no way to tell what version of flank was used in a run. The step could run `flank --version` at the start which prints the current version to the console.

**Comment by fehersanyi-bitrise** [comment]
Thanks @bootstraponline I created a card for the tooling guys to add it! 🙃

**Comment by Szabadember** [comment]
Step is printing the following information:
* Step version
* Flank version to be downloaded
* Flank binary prints:
** version running
** commit hash of the running version
