### ISSUE TITLE
Test Reports

### ISSUE THREAD

**Issue by josinaldobarbosa** [bitrise-steplib/bitrise-step-flank#4]
Is there any way to put the generated report in test reports?

**Comment by Roland-Bak** [comment]
Hey there @josinaldobarbosa!

 Currently you the following steps can appear in Test Reports: 

- Xcode Test for iOS
- Android Unit Test
- iOS Device Testing
- Virtual Device Testing for Android

Using Flank with the Testing add-on is definitely planned though, and we'll let you know once it has been utilized 🙂

**Comment by josinaldobarbosa** [comment]
@Roland-Bak :+1:
