### ISSUE TITLE
Flank Bitrise step failing 100% of the time

### ISSUE THREAD

**Issue by prfarlow1** [bitrise-steplib/bitrise-step-flank#6]
Flank updated their base URL. Please merge in this PR https://github.com/bitrise-steplib/bitrise-step-flank/pull/5 and release an update. Right now, we're totally blocked from using this step as it is broken without this change

**Comment by lpusok** [comment]
Something is definitely broken if using the latest version, but based on some trial (https://github.com/TestArmada/flank/releases/download/latest/flank.jar is not available, however https://github.com/TestArmada/flank/releases/download/v20.05.0/flank.jar is) you might be able to work around by using a specific version like (v20.05.0).

**Comment by lpusok** [comment]
It seems https://github.com/Flank/flank/releases/latest/download/flank.jar is the correct URL. The TestArmada GitHub org is redirected to Flank, so that may not be the main issue here.

**Comment by prfarlow1** [comment]
This temporary workaround seems to have fixed the problem, thanks

**Comment by mefiblogger** [comment]
Hi 👋 @prfarlow1,

First of all, thank your for your patience! I have some news: our team has fixed the issue and I'm here to provide some context and details about it.

We updated the Flank repo URL and fixed the Flank download URL builder logic.

https://github.com/bitrise-steplib/bitrise-step-flank/releases/tag/0.1.1

**I close this issue as as the latest release should fix it. If you need more info or help, just open a new issue or get in touch with our Support Team.**

Thanks and happy building 🚀
Mefi
