### ISSUE TITLE
Step with `latest` version is pulling incorrect version

### ISSUE THREAD

**Issue by prfarlow1** [bitrise-steplib/bitrise-step-flank#7]
Right now in Flank, the latest version is 20.7.0, and there's a pre-release of 20.8.0.
![Screen Shot 2020-08-05 at 11 44 41 AM](https://user-images.githubusercontent.com/6036075/89434029-0f570b00-d711-11ea-85a1-74129d3b7d0f.png)

In the step documentation for the version parameter, it says this:
"Flank binary version. You can use any tag name that is available on https://github.com/Flank/flank/releases or latest which will download the latest non-pre-elease version." (unrelated, but there's also a typo)

Currently, the step is failing for me with a 404 because I have entered `latest` but it's still trying to pull 20.8.0

**Comment by bootstraponline** [comment]
Thanks for the detailed issue report! We are in the process of rebuilding the release infrastructure on top of GitHub Actions. As part of that, a tag for v20.8.0 was created without a corresponding release. I deleted the tag and will work with the team to resolve the issue.

I agree the bitrise step should only use the latest release, as you point out.
